### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by StephanHarrer**
Added information to enable 3th party MIBs. If you do not enable the 3th party MIB no values shown in XMC (HTML).

### CODE REVIEW

**Comment by StephanHarrer** [comment]
3thPartyMIB

**Comment by ZdenekPala** [comment]
Hi Stephan.

I suggest the following:
- we do have a note about "where to put mibs" in relevant subdirectories only for FlexViews where we use special MIBs.
- use Extreme Management Center instead of XMC (our marketing is pushing us that way)
- HTML based frontend is called OneView

I suggest the following text to be added to those subdirectories instead of the place you suggest it:
To enable the use of third party MIBs, go to "OneView->Administration->Options->SNMP", the option "use MyMIBS directory on the server" should be checked. Change of this value does need the service restart with"...
- Additional details are https://emc.extremenetworks.com/content/oneview/docs/admin/options/docs/ov_admin_options_snmp.html

Thank you for your cooperation.

**Comment by StephanHarrer** [comment]
Hello Zdenek,

that's fully ok for me.

Regards
Stephan

**Comment by ZdenekPala** [comment]
let me know if you like it.

**Comment by StephanHarrer** [comment]
Hello Zdenek,

I like your adaptations. I checked it in the Fortnet and Infoblox help file.

Best regards
Stephan Harrer


Mit freundlichen Gruessen / Best Regards
Stephan Harrer
Systemingenieur & Consultant

Tel.:

+49 (911) 647259-730

Mobil:

+49 (151) 17140265

Fax:

+49 (228) 42104-80

E-Mail:

s.harrer@Bell.de<mailto:s.harrer@Bell.de>

Web:

www.bell.de<http://www.bell.de/>


[cid:image001.jpg@01D551CA.47091980]

[footer]
[footer]
[footer]
BELL Computer-Netzwerke GmbH | Paulusstr. 22, 53227 Bonn | Deutschland

Geschäftsführer: Dipl. Ing. Tobias Gröne | Amtsgericht Bonn: HRB 6444

>>> Kennen Sie unsere neuen Durchwahlen? ...bitte klicken Sie HIER<https://www.bell.de/die-neuen-nummern/>! <<<




Von: Zdenek Pala [mailto:notifications@github.com]
Gesendet: Dienstag, 13. August 2019 11:18
An: extremenetworks/XMC-Report-Views <XMC-Report-Views@noreply.github.com>
Cc: Stephan Harrer <S.Harrer@Bell.de>; Author <author@noreply.github.com>
Betreff: Re: [extremenetworks/XMC-Report-Views] Update README.md (#4)


let me know if you like it.

**Pull request merged**
